name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  terraform_run:
    runs-on: ubuntu-22.04
    steps:
      - uses: hashicorp/setup-terraform@v3
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: "us-east-1"
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - uses: actions/checkout@v4
      - run: terraform init
      - run: terraform apply -auto-approve
      - run: sleep 120s
      - run: terraform destroy -auto-approve
      - run: exit
